// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQYhYL9wVoOvBEg8tMja-6NtAIqpSeWQ',
    appId: '1:920401958084:web:a5eff634e4c1c97ca12591',
    messagingSenderId: '920401958084',
    projectId: 'urubudopix',
    authDomain: 'urubudopix.firebaseapp.com',
    storageBucket: 'urubudopix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd1QmL7Yqee1Lg55gAKh19mvakTw31I8Y',
    appId: '1:920401958084:android:a3373d2701f03bfea12591',
    messagingSenderId: '920401958084',
    projectId: 'urubudopix',
    storageBucket: 'urubudopix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVcLMzhOU7i8E18XL5Zzil6pwT8X87cwI',
    appId: '1:920401958084:ios:0fced228958bfa39a12591',
    messagingSenderId: '920401958084',
    projectId: 'urubudopix',
    storageBucket: 'urubudopix.firebasestorage.app',
    iosBundleId: 'com.example.urubudopix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVcLMzhOU7i8E18XL5Zzil6pwT8X87cwI',
    appId: '1:920401958084:ios:0fced228958bfa39a12591',
    messagingSenderId: '920401958084',
    projectId: 'urubudopix',
    storageBucket: 'urubudopix.firebasestorage.app',
    iosBundleId: 'com.example.urubudopix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKQYhYL9wVoOvBEg8tMja-6NtAIqpSeWQ',
    appId: '1:920401958084:web:79eca252759627a8a12591',
    messagingSenderId: '920401958084',
    projectId: 'urubudopix',
    authDomain: 'urubudopix.firebaseapp.com',
    storageBucket: 'urubudopix.firebasestorage.app',
  );
}
